[package]
name = "axum-asset"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
axum-asset-derive.workspace = true
axum-extra.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tokio.workspace = true
tower.workspace = true
