[package]
name = "axum-asset-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
hex.workspace = true
mime_guess.workspace = true
proc-macro2.workspace = true
quote.workspace = true
sha2.workspace = true
syn.workspace = true
walkdir.workspace = true
